import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from '@/styles/main.module.scss'
import React from "react";
import Loader from "@/widgets/Loader/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${inter.className} ${styles.app}`}>
        <React.Suspense fallback={<Loader />}>
          {children}
        </React.Suspense>
      </body>
    </html>
  );
}
